name: travelee
description: Travelee is an Android app to create a modern travel experience for travelers by applying some advanced technologies.

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.1.1
  flutter_localizations:
    sdk: flutter
  
  intl: ^0.17.0 # Add this line
  cupertino_icons: ^1.0.3
  location: ^4.1.1
  path_provider: ^2.0.1
  wakelock: ^0.5.1
  
  augmented_reality_plugin_wikitude:
    path: ./plugin/augmented_reality_plugin_wikitude/
    
  url_launcher: ^6.0.10
  fancy_bottom_navigation: ^0.3.3
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  settings_ui: ^1.0.0
  provider: ^6.0.1
  googleapis_auth: ^1.2.0
  googleapis: ^6.0.0
  image_picker: ^0.8.4+1
  video_player: ^2.2.3
  google_sign_in: ^5.1.0
  font_awesome_flutter: ^9.2.0
  firebase_core: ^1.10.2
  firebase_auth: ^3.3.0
  fluttertoast: ^8.0.8
  cloud_firestore: ^3.1.1
  sign_button: ^2.0.2
  shimmer: ^2.0.0
  html: ^0.15.0
  flutter_local_notifications: ^9.2.0
  flutter_image: ^4.1.0
  cached_network_image: ^3.2.0
  another_flushbar: ^1.10.28
  flutter_svg: ^0.22.0
  flutter_rating_bar: ^4.0.0
  rating_dialog: ^2.0.3
  line_awesome_flutter: ^2.0.0
  share_plus: ^3.0.1
  material_floating_search_bar: ^0.3.6
  dio: ^4.0.4
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.9
  flutter_google_places: ^0.3.0
  uuid: ^3.0.6
  favorite_button: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  json_serializable: ^4.1.1
  flutter_icons:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - samples/
    - samples/experience/
    - samples/experience/styles/
    - samples/experience/scripts/
    - samples/experience/fonts/lato/
    - samples/experience/augmentation-trackers/
    - samples/experience/augmentation-trackers/8.0/
    - samples/experience/augmentation-assets/92247863_chinese_heritage_centre/62333a70b2fd1d005546caaa/
    - samples/experience/augmentation-assets/92247863_chinese_heritage_centre/62333e7fb2fd1d005546cb6a/
    - samples/experience/augmentation-assets/92247863_chinese_heritage_centre/62333202b2fd1d005546be2a/
    - samples/customized/
    - samples/customized/js/
    - samples/customized/css/
    - samples/customized/assets/
    - samples/friend/
    - samples/friend/js/
    - samples/friend/css/
    - samples/friend/assets/
    - samples/mrt/
    - samples/mrt/js/
    - samples/mrt/css/
    - samples/mrt/assets/
    - samples/mall/
    - samples/mall/js/
    - samples/mall/css/
    - samples/mall/assets/
    - samples/landmark/
    - samples/landmark/js/
    - samples/landmark/css/
    - samples/landmark/assets/
    - assets/data/
    - assets/icons/
    - assets/fonts/Poppins/
  
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700